version: "3.3"
services:
  mysql:
    container_name: "mysql"
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "teste"
      MYSQL_PASSWORD: "senha_segura"
      MYSQL_ROOT_PASSWORD: "senha_segura_root"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - backend

  app:
    build: ./server
    container_name: "app"
    environment:
      DATABASE_HOST: "mysql://teste:senha_segura@mysql:3306/db"
    ports:
      - 3333:3333
    depends_on:
      - "mysql"
    command: ./wait-for.sh mysql:3306 -- node .  
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
